import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Josefin_Sans } from "next/font/google";
import { Ubuntu } from "next/font/google";

const ubuntu = Ubuntu({
  subsets:["latin"],
  weight:["300","400","500","700"],
  variable:"--font-ubuntu",
})

const josefin = Josefin_Sans({
subsets:["latin"],
weight:["300"],
variable:"--font-josefin",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tesfa Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefin.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
