import type { Metadata } from "next";
import "./globals.css";
import { Josefin_Sans } from "next/font/google";


const josefin = Josefin_Sans({
subsets:["latin"],
weight:["300"],
variable:"--font-josefin",
});

export const metadata: Metadata = {
  title: "Tesfa Website",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Images/tesfaLogo.png"/>
      </head>
      <body
        className={`${josefin.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
