import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Josefin_Sans } from "next/font/google";
import { Ubuntu } from "next/font/google";
import { icons } from "lucide-react";


const josefin = Josefin_Sans({
subsets:["latin"],
weight:["300"],
variable:"--font-josefin",
});

export const metadata: Metadata = {
  title: "Tesfa Website",
  description: "Generated by create next app",
   icons: {
    icon: "/Images/TesfaLogo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefin.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
